services:
  app:
    build: .
    container_name: ${APP_NAME:-be-sign-file}-app
    ports:
      - ${GOLANG_PORT:-8888}:8888
    depends_on:
      - postgres

  postgres:
    hostname: postgres
    container_name: ${APP_NAME:-be-sign-file}-db
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  db_data: